-- Passos 2-5 (Adriana, 24/09/2026): pessoas sem empresa com e-mail corporativo -> empresa pelo domínio.
-- Decisão por domínio: empresa do HubSpot quando existe (nome do HubSpot; 3 nomes-sujeira do HubSpot
-- — Sp, Vb, Zf — gravam o nome correto e vão para o passo 10), senão empresa já existente em
-- pessoas.empresas (domínio ou nome_chave), senão empresa nova (Lusha quando houve match; busca na web).
create temp table _m (dom_email text, dom_emp text, nome text, hs text, forcar boolean, lusha_id text, func int,
  setor_bruto text, setor text, cidade text, uf text, pais text, porte text) on commit drop;
insert into _m values
('2aholding.com','2aholding.com','2A Holding',null,false,null,null,null,null,null,null,null,null),
('3scorporate.com','3scorporate.com','3S Corp','56534261549',false,null,null,null,null,null,null,null,null),
('aambulanciasmban.com.br','ambulanciasmban.com.br','MBAN Emergências Médicas',null,false,null,null,null,null,null,null,null,null),
('ambulanciasmban.com.br','ambulanciasmban.com.br','MBAN Emergências Médicas',null,false,null,null,null,null,null,null,null,null),
('adv.feltrimcorrea.com.br','feltrimcorrea.com.br','Feltrim Correa Advogados',null,false,'v1.Lit3AFr_3leJxOH_XPBrdulBCd8y32Pq',26,'Business Services','Consultoria e serviços empresariais','Sao Paulo','SP','Brazil','até 100'),
('afap.ap.gov.br','afap.ap.gov.br','Agência de Fomento do Amapá (AFAP)',null,false,null,null,null,null,null,null,null,null),
('agerba.ba.gov.br','agerba.ba.gov.br','Agerba',null,false,'v1.xpheeoxK9teRF6lhWSKE6wKyVN1hgm5Olg',138,'Government','Setor público',null,'BA','Brazil','101–500'),
('alfaparf.com.br','alfaparf.com.br','Alfaparf Milano',null,false,null,null,null,null,null,null,null,null),
('almavivasolutions.com.br','almavivasolutions.com.br','Almaviva Solutions',null,false,'v1.9BlbkhdlwKBDHBUU6D2YuZrxZ5xjawI',565,'Technology, Information & Media','Tecnologia','Sao Paulo','SP','Brazil','501–1.000'),
('alvaesg.com.br','alvaesg.com.br','Alva Consultoria',null,false,'v1.X0c6Cht7sQA36ZZYt03ypkLxFaYMgwzXxg',3,'Business Services','Consultoria e serviços empresariais','Sao Paulo','SP','Brazil','até 100'),
('ap.sebrae.com.br','sebrae.com.br','Sebrae','56533700954',false,null,null,null,null,null,null,null,null),
('apiceadc.com.br','apiceadc.com.br','Ápice ADC',null,false,null,null,null,null,null,null,null,null),
('appiancapitalbrazil.com','appiancapitalbrazil.com','Appian Capital Brazil',null,false,null,null,null,null,null,null,null,null),
('aramisin.com.br','aramisinc.com.br','Aramis',null,false,null,null,null,null,null,null,null,null),
('aramisinc.com.br','aramisinc.com.br','Aramis',null,false,null,null,null,null,null,null,null,null),
('arraesadvogados.com.br','arraesadvogados.com.br','Arraes & Centeno Advogados',null,false,null,null,null,null,null,null,null,null),
('assembleia.pr.leg.br','assembleia.pr.leg.br','Assembleia Legislativa do Paraná',null,false,'v1.fV-t7Lsg8A20xoHFqEcOW8VpaScukduJ',735,'Government','Setor público','Curitiba','PR','Brazil','501–1.000'),
('attoperformance.com.br','attoperformance.com.br','Atto Performance',null,false,'v1.sjTeq3IGAJMPfG6OLgRKy83WYnYESghqxg',1,'Business Services','Consultoria e serviços empresariais',null,null,'Brazil','até 100'),
('averisamericas.com','averisamericas.com','Averis Americas',null,false,null,null,null,null,null,null,null,null),
('ba.sebrae.com.br','sebrae.com.br','Sebrae','56533700954',false,null,null,null,null,null,null,null,null),
('bd.com','bd.com','BD','56534358277',false,null,null,null,null,null,null,null,null),
('bemstartglobal.com.br','bemstartglobal.com.br','BemStart Global',null,false,null,null,null,null,null,null,null,null),
('beyondcorporate.com.be','beyondcorporate.com.br','Beyond Corporate',null,false,null,null,null,null,null,null,null,null),
('beyondcorporate.com.br','beyondcorporate.com.br','Beyond Corporate',null,false,null,null,null,null,null,null,null,null),
('bloominbrands.com.br','bloominbrands.com.br','Bloomin'' Brands Brasil (Outback)',null,false,null,null,null,null,null,null,null,null),
('boehringr-ingelheim.com','boehringer-ingelheim.com','Boehringer Ingelheim','54905263361',false,null,null,null,null,null,null,null,null),
('boehringer-ingelheim.com','boehringer-ingelheim.com','Boehringer Ingelheim','54905263361',false,null,null,null,null,null,null,null,null),
('br.estee.com','estee.com','Estée Lauder','56822650297',false,null,null,null,null,null,null,null,null),
('br.gestamp.com','gestamp.com','Gestamp',null,false,'v1.mCv8TII9tZuAXjYbhigpVJWq6lOMOg',17864,'Manufacturing','Indústria','Madrid',null,'Spain','+10.000'),
('br.gt.com','gt.com','Grant Thornton','56533762625',false,null,null,null,null,null,null,null,null),
('br.mcd.com','mcd.com','Arcos Dorados (McDonald''s)','57532120380',false,null,null,null,null,null,null,null,null),
('br.pvmgrp.com','pvmgrp.com','Perfetti Van Melle','56534317184',false,null,null,null,null,null,null,null,null),
('br.roca.com','roca.com','Roca','56834897719',false,null,null,null,null,null,null,null,null),
('br.schindler.com','schindler.com','Schindler','56533789483',false,null,null,null,null,null,null,null,null),
('br.zurich.com','zurich.com','Zurich Seguros','57544118626',false,null,null,null,null,null,null,null,null),
('buw.com.br','buw.com.br','Bier & Wein',null,false,'v1.jGAwqA03kcEhR9S_iRJfZpWGZ3kfmsQ',51,'Retail & Wholesale Trade','Varejo e atacado','Sao Paulo','SP','Brazil','até 100'),
('bwg.vom.br','bwg.com.br','BWG','54905263259',false,null,null,null,null,null,null,null,null),
('camarachinesa.com','camarachinesa.com','Câmara Chinesa de Comércio do Brasil',null,false,null,null,null,null,null,null,null,null),
('carpaconsulroria.com.br','carpaconsultoria.com.br','Carpa Consultoria','56315690309',false,null,null,null,null,null,null,null,null),
('cc.eduzz.com','eduzz.com','Eduzz','54896785278',false,null,null,null,null,null,null,null,null),
('ccccsa.com.br','ccccsa.com.br','CCCC South America',null,false,null,null,null,null,null,null,null,null),
('ce.sebrae.com.br','sebrae.com.br','Sebrae','56533700954',false,null,null,null,null,null,null,null,null),
('columbiatransportes.com.br','columbiatransportes.com.br','Columbia Transportes',null,false,null,null,null,null,null,null,null,null),
('confab.com.br','confab.com.br','Tenaris Confab','57340729354',false,null,null,null,null,null,null,null,null),
('conhecimentovivo.org','conhecimentovivo.org','Conhecimento Vivo',null,false,null,null,null,null,null,null,null,null),
('consultoriaalliamce.com.br','consultoriaalliance.com.br','Consultoria Alliance','56732546960',false,null,null,null,null,null,null,null,null),
('contato.pontodoisvideo.com.br','pontodoisvideo.com.br','Ponto Dois Comunicação',null,false,'v1.T6KaQ0iW4Xmnfr4k5NyGlVEPAZb0GtB8',2,'Technology, Information & Media','Tecnologia','Sao Paulo','SP','Brazil','até 100'),
('coopsp.coop.br','coopsp.coop.br','Coop - Cooperativa de Consumo',null,false,null,null,null,null,null,null,null,null),
('credsystem.com','credsystem.com','Credsystem','56533780256',false,null,null,null,null,null,null,null,null),
('crowncork.com.br','crowncork.com.br','Crown Embalagens',null,false,null,null,null,null,null,null,null,null),
('daftrucks.com','daftrucks.com','DAF Caminhões',null,false,'v1.UyARlmnTU3oSoZ5VqM1kzgZkJ_m-d3wk',6472,'Manufacturing','Indústria','Eindhoven',null,'Netherlands','5.001–10.000'),
('dbacomp.br','dbacomp.com.br','DBACOMP Solutions',null,false,null,null,null,null,null,null,null,null),
('dbacomp.com.br','dbacomp.com.br','DBACOMP Solutions',null,false,null,null,null,null,null,null,null,null),
('defensoria.sc.gov.br','defensoria.sc.gov.br','Defensoria Pública de Santa Catarina',null,false,'v1.xGJRAlkS2EOOpw1Whs4GaQOh70AnYZx6',263,'Government','Setor público','Florianopolis','SC','Brazil','101–500'),
('designforpeople.com.br','designforpeople.com.br','Design For People',null,false,'v1.T0EQ9pv7YeLWltjEcbNeT83TYO-88rBW',3,'Education','Educação e pesquisa','Sao Paulo','SP','Brazil','até 100'),
('detran.ba.gov.br','detran.ba.gov.br','Detran Bahia',null,false,'v1.bqOuYRagnAyf77KqHwJq7Io3rG4V7MSv',259,'Government','Setor público','Salvador','BA','Brazil','101–500'),
('dsregionais.com.br','dsregionais.com.br','DSR Distribuidora de Supergelados Regionais',null,false,'v1.-ei_LTgfkLUjVQyS5X9KyyArnTUuABIr',15,'Hospitality','Serviços ao consumidor e hospitalidade',null,'RJ','Brazil','até 100'),
('dwyeromega.com','dwyeromega.com','DwyerOmega',null,false,'v1.FXgv0_-dvKFn_upuGRRTRIGect3gkaeo',977,'Manufacturing','Indústria','Michigan City','IN','United States','501–1.000'),
('eaimkt.com.br','eaimkt.com.br','EAÍ?! Content Experience','56397556147',false,null,null,null,null,null,null,null,null),
('ebbranding.com.br','ebbranding.com.br','EBB - Experience Beyond Business',null,false,null,null,null,null,null,null,null,null),
('eduzz.com.br','eduzz.com','Eduzz','54896785278',false,null,null,null,null,null,null,null,null),
('egv.com.br','egv.com.br','Escola Granja Viana',null,false,'v1.mO2WeMXpLsRd0PSz7F5OL9-ZM7sVBigM',4,'Education','Educação e pesquisa',null,null,'Brazil','até 100'),
('epstemia.com.br','epstemia.com.br','Epstemia',null,false,null,null,null,null,null,null,null,null),
('estrategia.eti.br','estrategia.eti.br','Estratégia TI',null,false,null,null,null,null,null,null,null,null),
('fenomenabrasil.com.br','fenomenabrasil.com.br','Fenômena Brasil',null,false,null,null,null,null,null,null,null,null),
('fineandyou.com.br','fineandyou.com.br','FineAndYou',null,false,'v1.xATDOMP1zvVJkq0NP-YdqYf8pila-pgXTQ',3,'Healthcare','Saúde e bem-estar',null,null,'Brazil','até 100'),
('forvismazars.com.br','forvismazars.com','Forvis Mazars','56769307494',false,null,null,null,null,null,null,null,null),
('fovismazars.com','forvismazars.com','Forvis Mazars','56769307494',false,null,null,null,null,null,null,null,null),
('franksintl.com','franksintl.com','Frank''s International',null,false,null,null,null,null,null,null,null,null),
('g.globo','globo','Globo','56534295376',false,null,null,null,null,null,null,null,null),
('gadeconsultoria.com','gadeconsultoria.com','Gade Consultoria',null,false,null,null,null,null,null,null,null,null),
('getlearnworlds.com','getlearnworlds.com','LearnWorlds','55275987461',false,null,null,null,null,null,null,null,null),
('granadophebo.com.br','granadophebo.com.br','Granado',null,false,null,null,null,null,null,null,null,null),
('grupoegb.com','grupoegb.com','Esportes Gaming Brasil',null,false,null,null,null,null,null,null,null,null),
('grupolunelli.com','grupolunelli.com','Grupo Lunelli',null,false,'v1.__pJ0TwMEG-OxtoSmE9EuOTju0QoeG5i',31,'Manufacturing','Indústria','Maracanau','CE','Brazil','até 100'),
('grupotbx.com.br','grupotbx.com.br','Grupo TBX',null,false,null,null,null,null,null,null,null,null),
('handspapeis.com.br','handspapeis.com.br','Hands Papéis',null,false,'v1.8ep9U3bXN__NlYATIP1AIQbBxPd0vV0',6,'Manufacturing','Indústria','Sao Paulo','SP','Brazil','até 100'),
('haptuscontabilidade.com.br','haptuscontabilidade.com.br','Haptus Contabilidade',null,false,null,null,null,null,null,null,null,null),
('hc.fm.usp.br','hc.fm.usp.br','Hospital das Clínicas da FMUSP',null,false,null,null,null,null,null,null,null,null),
('hdi-yelum.com.br','hdi-yelum.com.br','Yelum Seguros',null,false,null,null,null,null,null,null,null,null),
('hdiyelum.com.br','hdi-yelum.com.br','Yelum Seguros',null,false,null,null,null,null,null,null,null,null),
('heleon.com','haleon.com','Haleon','57650876929',false,null,null,null,null,null,null,null,null),
('ima.sp.gov.br','ima.sp.gov.br','IMA - Informática de Municípios Associados','57540246396',true,null,null,null,null,null,null,null,null),
('incontri.com.br','incontri.com.br','Incontri',null,false,null,null,null,null,null,null,null,null),
('institutocuidareacolher.org','institutocuidareacolher.org','Instituto Cuidar e Acolher',null,false,'v1.kt-zXYMD4_gh1k3cH5vXLVLXtvpPye_gVg',3,'Community & Nonprofit Organizations','Terceiro setor',null,null,'Brazil','até 100'),
('ipac.ba.gov.br','ipac.ba.gov.br','IPAC Bahia',null,false,null,null,null,null,null,null,null,null),
('ismsaude.org.br','ismsaude.org.br','Instituto Social Mais Saúde (ISMS)',null,false,null,null,null,null,null,null,null,null),
('itineraconstrucoes.com.br','itineraconstrucoes.com.br','Itinera Construções',null,false,null,null,null,null,null,null,null,null),
('its.jnj.com','jnj.com','Johnson & Johnson','57342734760',false,null,null,null,null,null,null,null,null),
('jdecoffee.com','jdecoffee.com','JDE Peet''s',null,false,null,null,null,null,null,null,null,null),
('kcj.com.br','kcj.com.br','KCJ Advogados',null,false,null,null,null,null,null,null,null,null),
('letras.ufrj.br','ufrj.br','UFRJ',null,false,'v1.HQLSDb4u1AYtk3IWAlrVYhusiAwgdTyY',10522,'Education','Educação e pesquisa','Rio de Janeiro','RJ','Brazil','+10.000'),
('lyrymedicina.com.br','lyrymedicina.com.br','Lyry Medicina Aplicada',null,false,null,null,null,null,null,null,null,null),
('machadao.com.br','machadao.com.br','Machadão Atacadista',null,false,'v1.LYDUyT1oko9GofY58ZZsxD45NDwXG6O1',419,'Retail & Wholesale Trade','Varejo e atacado','Alta Floresta','MT','Brazil','101–500'),
('maisidiversidade.com.br','maisdiversidade.com.br','Mais Diversidade','54913307911',false,null,null,null,null,null,null,null,null),
('maisdiversidade.com.br','maisdiversidade.com.br','Mais Diversidade','54913307911',false,null,null,null,null,null,null,null,null),
('medic360.com.bt','medic360.com.br','Medic360',null,false,null,null,null,null,null,null,null,null),
('medic360.com.br','medic360.com.br','Medic360',null,false,null,null,null,null,null,null,null,null),
('mercermarshbeneficios.com','mercermarshbeneficios.com','Mercer Marsh Benefícios','56746224525',false,null,null,null,null,null,null,null,null),
('migramobility.com.br','migramobility.com.br','Migra Mobility',null,false,null,null,null,null,null,null,null,null),
('moveer.com.br','moveer.com.br','Moveer',null,true,null,null,null,null,null,null,null,null),
('moveisesplanada.com.br','moveisesplanada.com.br','Esplanada Móveis',null,false,'v1.uebIVyx24aLT70sjvSl0QlUeHdnk6uTK',3,'Retail & Wholesale Trade','Varejo e atacado','Jundiaí','SP','Brazil','até 100'),
('muhtua.com.br','muhtua.com.br','Muhtua',null,false,'v1.V4FIPxtvVeUsS-DYdqGJE9xSG2ea3WS4mg',3,'Business Services','Consultoria e serviços empresariais','Florianópolis','SC','Brazil','até 100'),
('multiplicaseguros.com.br','multiplicaseguros.com.br','Multiplica Seguros',null,false,null,null,null,null,null,null,null,null),
('necgtarinabrasil.com.br','nectarinabrasil.com.br','Nectarina Cultural',null,false,'v1.nON5FGPk6GpfsyAcrrdUccJ4fWZPb-1F9w',2,'Hospitality','Serviços ao consumidor e hospitalidade','Sao Paulo','SP','Brazil','até 100'),
('nectarinabrasil.com.br','nectarinabrasil.com.br','Nectarina Cultural',null,false,'v1.nON5FGPk6GpfsyAcrrdUccJ4fWZPb-1F9w',2,'Hospitality','Serviços ao consumidor e hospitalidade','Sao Paulo','SP','Brazil','até 100'),
('nelorecometa.com.br','nelorecometa.com.br','Nelore Cometa',null,false,'v1.H_bb1Yav5rn-jllmDsRSPYKVyn8KDjs7',13,'Farming, Ranching, Forestry','Agronegócio','Cáceres','MT','Brazil','até 100'),
('odaralifestyle.com','odaralifestyle.com','Odara Lifestyle',null,false,null,null,null,null,null,null,null,null),
('oportunaconsultoria.com.br','oportunaconsultoria.com.br','Oportuna Consultoria',null,false,null,null,null,null,null,null,null,null),
('opussol.com.br','opussol.com.br','Instituto Opus',null,false,'v1.IYz5v5nNp8oDXu4i2p-M_5YGCJY6lufZ',7,'Business Services','Consultoria e serviços empresariais','São Paulo','SP','Brazil','até 100'),
('otimizamarketing.com.br','otimizamarketing.com.br','Otimiza Marketing',null,false,null,null,null,null,null,null,null,null),
('parisatacado.com.br','parisatacado.com.br','Paris Atacado',null,false,'v1.iJVyF5G8RluwUpF-T2WRQvyR3UTb6Zvg',7,'Retail & Wholesale Trade','Varejo e atacado','Leônidas Marques','PR','Brazil','até 100'),
('passofundoagro.com.br','passofundoagro.com.br','Passo Fundo Agro',null,false,'v1.W__bDH9Dtnt_y0U3jA3SR9TQ8RIw-m5B',49,'Farming, Ranching, Forestry','Agronegócio','Luis Eduardo Magalhaes','BA','Brazil','até 100'),
('polopalestrantes.com','polopalestrantes.com','Polo Palestrantes',null,false,null,null,null,null,null,null,null,null),
('portalglobocidade.com.br','portalglobocidade.com.br','Portal Globo Cidade',null,false,null,null,null,null,null,null,null,null),
('portodesantos.gov.br','portodesantos.gov.br','Autoridade Portuária de Santos',null,false,null,null,null,null,null,null,null,null),
('posherapp.com','posherapp.com','Posher',null,false,'v1.N37cYJ0wHBoA7f7eOIE-A1ZNV1gH7PM8',65,'Business Services','Consultoria e serviços empresariais','Sao Paulo','SP','Brazil','até 100'),
('proconnecengenharia.com.br','proconnectengenharia.com.br','ProConnect Engenharia',null,false,null,null,null,null,null,null,null,null),
('proconnectengenharia.com.br','proconnectengenharia.com.br','ProConnect Engenharia',null,false,null,null,null,null,null,null,null,null),
('ps.rolls-royce.com','rolls-royce.com','Rolls-Royce',null,false,'v1.LfwAo0y2vxq_KnL4N3AIYc8sFdIUmV0F',31913,'Manufacturing','Indústria','London','ENG','United Kingdom','+10.000'),
('psicoespqco.com.br','psicoespaco.com.br','Psicoespaço','54905263286',false,null,null,null,null,null,null,null,null),
('psyquesaudemental.com.br','psyquesaudemental.com.br','Psyque Saúde Mental',null,false,'v1.oyK3Iu3WZsl9ieLjGIrk5-60QVWkODTvuA',1,'Education','Educação e pesquisa',null,null,'Brazil','até 100'),
('quaehuman.com.br','quaehuman.com.br','Quae Human',null,false,null,null,null,null,null,null,null,null),
('quaestia.com','quaestia.com','Quaestia',null,false,'v1.sAB-a2VwhrOa_QIG7HJvBaZZxQmWXWI8',1,'Business Services','Consultoria e serviços empresariais',null,null,'Brazil','até 100'),
('queirozgalvao.com','queirozgalvao.com','Queiroz Galvão',null,false,'v1.uWXJImqoGYrRV_VijOow179Fv4i5jiNX',107,'Construction','Construção e imobiliário','Rio de Janeiro','RJ','Brazil','101–500'),
('revoluh.com','revoluh.com','Revoluh',null,false,null,null,null,null,null,null,null,null),
('rezendebarbosa.com.br','rezendebarbosa.com.br','Rezende Barbosa',null,false,null,null,null,null,null,null,null,null),
('risknexus.com.br','risknexus.com.br','Risk Nexus',null,false,null,null,null,null,null,null,null,null),
('rochsmiranda.adv.br','rochamiranda.adv.br','Rocha Miranda Advogados',null,false,null,null,null,null,null,null,null,null),
('rochamiranda.adv.br','rochamiranda.adv.br','Rocha Miranda Advogados',null,false,null,null,null,null,null,null,null,null),
('rp.ribeiraopreto.sp.gov.br','ribeiraopreto.sp.gov.br','Prefeitura de Ribeirão Preto',null,false,'v1.w_IETfQdhxFz295Ivx38HdXlwIKdX4cB',3325,'Government','Setor público','Ribeirão Preto','SP','Brazil','1.001–5.000'),
('sa.cushwake.com','cushwake.com','Cushman & Wakefield',null,false,'v1.iHCqyn4WcsG3HrPet4L76Doaxj_0z5HT-A',null,null,null,'New York','NY','United States',null),
('saberaprendizes.org.com','saberaprendizes.org.br','Saber Aprendizes','54898486897',false,null,null,null,null,null,null,null,null),
('saladcollab.com.br','saladcollab.com.br','Salad Collab',null,false,null,null,null,null,null,null,null,null),
('sas.upenn.edu','upenn.edu','University of Pennsylvania',null,false,'v1.KSMDM5kH-6i69g6NPkFItq-VfwfbavmI',22580,'Education','Educação e pesquisa','Philadelphia','PA','United States','+10.000'),
('sc.sebrae.com.br','sebrae.com.br','Sebrae','56533700954',false,null,null,null,null,null,null,null,null),
('sc.usp.br','usp.br','Universidade de São Paulo','56685324576',false,null,null,null,null,null,null,null,null),
('sescoop.br','sescoop.coop.br','Sescoop',null,false,null,null,null,null,null,null,null,null),
('sescoop.coop.br','sescoop.coop.br','Sescoop',null,false,null,null,null,null,null,null,null,null),
('signium.com.br','signium.com.br','Signium Brasil',null,false,null,null,null,null,null,null,null,null),
('smartcolors.com.br','smartcolors.com.br','Smartcolors',null,false,null,null,null,null,null,null,null,null),
('sme.prefeitura.sp.gov.br','prefeitura.sp.gov.br','Prefeitura de São Paulo','57897609854',false,null,null,null,null,null,null,null,null),
('spacehrsolutions.com','spacehrsolutions.com','Space HR Solutions',null,false,null,null,null,null,null,null,null,null),
('stapfconsultoriarh.com.br','stapfconsultoriarh.com.br','Stapf Consultoria RH',null,false,null,null,null,null,null,null,null,null),
('strongrh.com.br','strongrh.com.br','Strong Soluções em RH',null,false,null,null,null,null,null,null,null,null),
('superatacadonovaera.com.br','superatacadonovaera.com.br','Nova Era Superatacado',null,false,null,null,null,null,null,null,null,null),
('syntegon.com','syntegon.com','Syntegon',null,false,'v1.rCppuQe4Fq_pkhNgwVyC0gFwsEyo9QJE',4119,'Manufacturing','Indústria','Stuttgart','BW','Germany','1.001–5.000'),
('thyssenkrupp-automotive.com','thyssenkrupp-automotive.com','thyssenkrupp','56533788039',false,null,null,null,null,null,null,null,null),
('totvs.com.br','totvs.com.br','TOTVS','57248720156',false,null,null,null,null,null,null,null,null),
('unimedmg.coop.br','unimedmg.coop.br','Unimed Federação Minas',null,false,null,null,null,null,null,null,null,null),
('unimedsulcapixaba.coop.br','unimedsulcapixaba.coop.br','Unimed Sul Capixaba',null,false,'v1.O0Kn3AtTMIWks29JSfzcH5XYGMKrSq28',4,'Healthcare','Saúde e bem-estar','Cachoeiro de Itapemirim','ES','Brazil','até 100'),
('vb.com.br','vb.com.br','VB Serviços','57543654069',true,null,null,null,null,null,null,null,null),
('vialto.com','vialto.com','Vialto Partners',null,false,'v1.EA9vfI_HFzW_EA8viIILUAfS1LjwmdY',5977,'Business Services','Consultoria e serviços empresariais','London','ENG','United Kingdom','5.001–10.000'),
('vieirasoutoadvogados.com.br','vieirasoutoadvogados.com.br','Vieira Souto Advogados',null,false,null,null,null,null,null,null,null,null),
('vlilogistica.com','vlilogistica.com','VLI Logística','56533952395',false,null,null,null,null,null,null,null,null),
('xwf.google.com','google.com','Google','54911605047',false,null,null,null,null,null,null,null,null),
('yahoo-inc.com','yahooinc.com','Yahoo',null,false,null,null,'Technology, Information & Media','Tecnologia','Sunnyvale','CA','United States','+10.000'),
('yannickathia.com.br','yannickathia.com.br','Yannick Athia Arquitetura',null,false,null,null,null,null,null,null,null,null),
('zebrahcontabilidade.com.br','zebrahcontabilidade.com.br','ZebraH Contabilidade',null,false,'v1.pQCIxMaUAPcGnkGBpVHoXZYK11lVS1vUQA',4,'Finance','Serviços financeiros e seguros','Assis','SP','Brazil','até 100'),
('zf.com','zf.com','ZF Group','57524321819',true,null,null,null,null,null,null,null,null);
-- empresa alvo
alter table _m add column eid uuid;
update _m set eid = e.id from pessoas.empresas e where _m.hs is not null and e.hubspot_company_id = _m.hs;
update _m set eid = (select e.id from pessoas.empresas e where lower(e.dominio) = _m.dom_emp order by e.hubspot_company_id nulls last limit 1)
 where eid is null;
update _m set eid = (select e.id from pessoas.empresas e where e.nome_chave = intelligence.texto_chave(_m.nome, true) order by e.hubspot_company_id nulls last limit 1)
 where eid is null;
create temp table _novas on commit drop as
 select distinct on (dom_emp) dom_emp, nome, lusha_id, func, setor_bruto, setor, cidade, uf, pais, porte from _m where eid is null order by dom_emp, lusha_id nulls last;
insert into pessoas.empresas (nome, dominio, setor, setor_bruto, funcionarios, cidade, uf, pais, origem, lusha_id, enriquecido_por, enriquecido_em, hubspot_pendente)
 select nome, dom_emp, setor, setor_bruto, func, cidade, uf, pais, 'dominio', lusha_id,
        case when lusha_id is not null then 'lusha' end, case when lusha_id is not null then now() end, true
   from _novas;
update _m set eid = e.id from pessoas.empresas e where _m.eid is null and e.origem='dominio' and lower(e.dominio) = _m.dom_emp;
-- pessoas
create temp table _p on commit drop as
 select p.id, p.empresa antes_empresa, p.empresa_id antes_id, m.eid, case when m.forcar then m.nome else e.nome end nome_final
   from pessoas.pessoas p
   join _m m on lower(split_part(p.email,'@',2)) = m.dom_email
   join pessoas.empresas e on e.id = m.eid
  where p.fundida_em is null and coalesce(btrim(p.empresa),'') = '';
update pessoas.pessoas p set empresa = x.nome_final, empresa_id = x.eid, atualizado_em = now() from _p x where p.id = x.id;
insert into public.mind_admin_audit (action, resource, record_id, record_label, before_data, after_data, request_id)
 select 'atualizar','pessoas_empresa_dominio', x.id::text, 'empresa pelo domínio do e-mail',
        jsonb_build_object('empresa', x.antes_empresa, 'empresa_id', x.antes_id), jsonb_build_object('empresa', x.nome_final, 'empresa_id', x.eid),
        '6b1f3c2e-2409-4e2a-9d05-240924000005'::uuid
   from _p x;
select (select count(*) from _novas) empresas_novas, (select count(*) from _p) pessoas_gravadas,
       (select count(*) from _m where eid is null) dominios_sem_empresa;
