-- O relatório do Yazo não traz id: o casamento com a agenda é pelo nome da sessão.
-- Os títulos abaixo são os do relatório, byte a byte (inclusive os espaços duplos),
-- para que o match por nome funcione sem heurística de normalização.

update summit_2026.sessions s set titulo = v.titulo, atualizado_em = now()
from (values
  ('d1-0900-abertura', 'Abertura'),
  ('d1-1130-conversas-dificeis', 'Conversas difíceis, times que crescem: Como transformar tensão em diálogo, aprendizagem e colaboração'),
  ('d1-1130-emocoes-positivas', 'O que emoções positivas têm a ver com performance? Como as emoções impactam a capacidade de execução e crescimento'),
  ('d1-1130-mensuracao-pgr', 'Da mensuração ao PGR: Como avaliar riscos psicossociais e definir prioridades de ação'),
  ('d1-1130-mensurar-intervir', 'Mensurar, intervir, provar: a metodologia Oxford para wellbeing como ativo de performance'),
  ('d1-1130-produtividade-sustentavel', 'Produtividade sustentável: Como manter performance sem esgotar pessoas'),
  ('d1-1130-sustenta-equipes', 'O que sustenta equipes de alta performance: Ferramentas de inteligência relacional para líderes'),
  ('d1-1130-trabalho-ainda', 'O trabalho ainda engaja? O que a maior pesquisa global sobre o mercado de trabalho revela sobre propósito, pertencimento e desempenho'),
  ('d1-1230-curadoria', 'Como incorporar a saúde mental à gestão de equipes'),
  ('d1-1230-nova-era', 'A nova era da alta performance: Como preparar corpo e mente para uma vida e carreira mais longevas'),
  ('d1-1230-virada-diversidade', 'A virada da diversidade: Estratégias de inclusão para alavancar performance, engajamento e vantagem competitiva'),
  ('d1-1430-modo-ativar', 'Modo Ativar: Uma experiência de respiração para recuperar presença, energia e foco.'),
  ('d1-1500-autonomia-desorganizacao', 'Como produzir sem se esgotar: Redesenhando o trabalho para culturas de bem-estar e alta performance'),
  ('d1-1500-economia-distracao', 'A economia da distração: Os mecanismos invisíveis que sabotam seu foco todos os dias'),
  ('d1-1500-falhar-melhor', 'Falhar melhor: Como transformar erros em aprendizagem sem reduzir a exigência'),
  ('d1-1500-lideranca-engajadora', 'Liderança engajadora: Como sustentar o engajamento no trabalho e o desempenho das equipes na prática.'),
  ('d1-1500-resiliencia-tempo', 'Resiliência em tempo real: Como manter clareza, flexibilidade e capacidade de resposta sob pressão'),
  ('d1-1500-seu-emprego', 'O seu emprego vai existir daqui a 5 anos? Como navegar a transformação do trabalho pela IA com agência, confiança e capacidade de adaptação'),
  ('d1-1500-tres-movimentos', 'Os três movimentos do líder que destravam aprendizagem coletiva'),
  ('d1-1530-trabalho-anos', 'Trabalho S/A: O que 26 anos ouvindo líderes revelam sobre carreira, gestão e o futuro do trabalho'),
  ('d1-1600-consciencia-finitude', 'Como a consciência da finitude transforma a forma de viver e as escolhas que fazemos'),
  ('d1-1600-curadoria', 'Saúde mental não é igual para todos:  Como trazer a diversidade para a conversa'),
  ('d1-1600-relacoes-sustentam', 'Relações que sustentam: A importância dos vínculos para a saúde emocional, financeira e no trabalho'),
  ('d1-1720-lideranca-consciente', 'Liderança Consciente: Autorregulação, pausa e autocompaixão na liderança'),
  ('d1-1810-mito-colaborador', 'O mito do colaborador resiliente: Por que burnout é um problema de desenho de trabalho, não de fraqueza individual'),
  ('d2-0900-quem-enxerga', 'Quem enxerga antes, lidera antes: Uma experiência que transforma percepção em estratégia'),
  ('d2-1130-bem-estar', 'Bem-estar baseado em evidência: Aprenda a desenhar intervenções que de fato funcionam'),
  ('d2-1130-comeca-agenda', 'Bem-estar começa na agenda: Como transformar intenção em prioridade organizacional'),
  ('d2-1130-curadoria', 'O que levamos de casa para o trabalho:  Histórias e valores que moldam a maneira de liderar'),
  ('d2-1130-feedback-falta', 'O feedback que falta: Como tornar visíveis as forças que sustentam o resultado'),
  ('d2-1130-onde-foi', 'Onde foi parar o seu foco: O que a neurociência mostra sobre o trabalho moderno'),
  ('d2-1130-riscos-psicossociais', 'Riscos psicossociais sem improviso: Como prevenir, estruturar responsabilidades e atender às exigências legais'),
  ('d2-1130-voce-aguenta', 'Você aguenta ser líder? Como manter o equilíbrio entre saúde mental e performance em um mundo cada vez mais acelerado'),
  ('d2-1230-curadoria', 'Ninguém deixa os filhos no estacionamento:  Parentalidade como estratégia de bem-estar e resultados'),
  ('d2-1230-lideranca-emocionalmente', 'Liderança emocionalmente madura: Autorregulação, limites saudáveis e equilíbrio sob pressão'),
  ('d2-1230-mulheres-abrem', 'Mulheres que abrem caminho: Como construir redes de transformação'),
  ('d2-1500-cultura-emocional', 'Cultura emocional: entre o engajamento e o burnout | Como emoções compartilhadas e práticas organizacionais positivas influenciam a experiência e a performance no trabalho.'),
  ('d2-1500-desalinhamentos-burnout', 'Os 6 desalinhamentos do burnout: Como ler e redesenhar o trabalho do seu time'),
  ('d2-1500-infraestrutura-performance', 'Infraestrutura de Performance: Desenho pessoal para executivos sob pressão crônica'),
  ('d2-1500-lider-arquiteto', 'O líder como arquiteto do trabalho: Rotinas para dar clareza, remover obstáculos e sustentar a performance'),
  ('d2-1500-seu-cerebro', 'Seu cérebro não foi feito para isso: O desencontro entre o cérebro humano e as exigências da vida moderna'),
  ('d2-1500-sobreviver-destruir', 'Sobreviver sem destruir o time: Como liderar quando o negócio está sob pressão'),
  ('d2-1500-trabalho-hibrido', 'Trabalho Híbrido sem Caos: Liderança, Colaboração e Ferramentas para uma Rotina Equilibrada'),
  ('d2-1600-conversas-corajosas', 'Conversas Corajosas, Times Fortes: Segurança psicológica, desconforto e performance'),
  ('d2-1600-curadoria', 'Liderança feminina em um futuro do trabalho líquido'),
  ('d2-1600-quem-esta', 'Quem está no controle? O desafio de construir uma relação saudável com a tecnologia'),
  ('d2-1640-florescendo-tempos', 'Florescendo em tempos de incerteza: Por que o otimismo continua sendo uma vantagem competitiva'),
  ('d2-1720-estrategia-pratica', 'Da estratégia à prática: Casos, decisões e aprendizados da alta liderança')
) as v(site_session_id, titulo)
where s.site_session_id = v.site_session_id
  and s.titulo is distinct from v.titulo;
