-- ESPELHO DO HUBSPOT. Gerado a partir do export de propriedades de 23/08/2026.
-- Tres tabelas: contato (150 props), negocio no pipeline de leads, negocio no historico.
-- Nenhuma delas e verdade canonica: crm.pessoas continua sendo a identidade.

create table if not exists crm.contato_espelho (
  id uuid primary key default gen_random_uuid(),
  pessoa_id uuid references crm.pessoas(id) on delete cascade,
  hubspot_id text not null unique,
  engagements_last_meeting_booked timestamptz,
  engagements_last_meeting_booked_campaign text,
  engagements_last_meeting_booked_medium text,
  engagements_last_meeting_booked_source text,
  first_conversion_date timestamptz,
  first_conversion_event_name text,
  hs_content_membership_notes text,
  hs_content_membership_status text,
  hs_feedback_last_ces_survey_date timestamptz,
  hs_feedback_last_ces_survey_follow_up text,
  hs_feedback_last_ces_survey_rating numeric,
  hs_feedback_last_nps_follow_up text,
  hs_feedback_last_nps_rating text,
  hs_feedback_last_survey_date timestamptz,
  hs_last_sales_activity_timestamp timestamptz,
  hs_sales_email_last_clicked timestamptz,
  hs_sales_email_last_opened timestamptz,
  hs_sales_email_last_replied timestamptz,
  hs_sequences_is_enrolled boolean,
  message text,
  notes_last_contacted timestamptz,
  notes_last_updated timestamptz,
  notes_next_activity_date timestamptz,
  num_contacted_notes numeric,
  num_notes numeric,
  hs_email_bad_address boolean,
  hs_email_bounce numeric,
  hs_email_click numeric,
  hs_email_customer_quarantined_reason text,
  hs_email_delivered numeric,
  hs_email_first_click_date timestamptz,
  hs_email_first_open_date timestamptz,
  hs_email_first_reply_date timestamptz,
  hs_email_first_send_date timestamptz,
  hs_email_hard_bounce_reason_enum text,
  hs_email_last_click_date timestamptz,
  hs_email_last_email_name text,
  hs_email_last_open_date timestamptz,
  hs_email_last_reply_date timestamptz,
  hs_email_last_send_date timestamptz,
  hs_email_open numeric,
  hs_email_optout boolean,
  hs_email_optout_1701138329 text,
  hs_email_optout_1701138330 text,
  hs_email_optout_1702074925 text,
  hs_email_optout_3137279076 text,
  hs_email_quarantined boolean,
  hs_email_quarantined_reason text,
  hs_email_replied numeric,
  hs_email_sends_since_last_engagement numeric,
  hs_email_type text,
  hs_emailconfirmationstatus text,
  hs_legal_basis text,
  hs_quarantined_emails text,
  hs_analytics_average_page_views numeric,
  hs_analytics_first_referrer text,
  hs_analytics_first_timestamp timestamptz,
  hs_analytics_first_touch_converting_campaign text,
  hs_analytics_first_url text,
  hs_analytics_first_visit_timestamp timestamptz,
  hs_analytics_last_referrer text,
  hs_analytics_last_timestamp timestamptz,
  hs_analytics_last_touch_converting_campaign text,
  hs_analytics_last_url text,
  hs_analytics_last_visit_timestamp timestamptz,
  hs_analytics_num_event_completions numeric,
  hs_analytics_num_page_views numeric,
  hs_analytics_num_visits numeric,
  hs_analytics_revenue numeric,
  hs_analytics_source text,
  hs_analytics_source_data_1 text,
  hs_analytics_source_data_2 text,
  hs_latest_source text,
  hs_latest_source_data_1 text,
  hs_latest_source_data_2 text,
  hs_latest_source_timestamp timestamptz,
  certificacao_avancada__progresso numeric,
  certificacao_lideranca_positiva_comprada text,
  certificacao_lideranca_positiva_elegivel text,
  certificado_lideranca_positiva__enps numeric,
  concluiu_as_3_formacoes text,
  formacao_1__enps numeric,
  formacao_1__progresso numeric,
  formacao_1__status text,
  formacao_1__ultimo_acesso date,
  formacao_2__enps numeric,
  formacao_2__progresso__clonado numeric,
  formacao_2__status text,
  formacao_2__ultimo_acesso date,
  formacao_3__enps numeric,
  formacao_3__progresso numeric,
  formacao_3__status text,
  formacao_3__ultimo_acesso date,
  formacao__produtos_comprados text,
  projeto_integrador_concluido text,
  total_de_formacoes_no_instituto numeric,
  comprou_ingressos_adicionais text,
  ingressos_comprados__2023 numeric,
  ingressos_comprados__2024 numeric,
  ingressos_comprados__2025 numeric,
  ingressos_comprados__2026 numeric,
  participou_de_mais_de_um_summit text,
  summit__categoria_do_ingresso text,
  summit__cortesia_anos text,
  summit__participacao_anual text,
  summit__patrocinio_anos text,
  tipo_de_entrada text,
  total_de_ingressos_comprados_lifetime numeric,
  total_de_summits_participados numeric,
  closedate timestamptz,
  days_to_close numeric,
  first_deal_created_date timestamptz,
  hs_buying_role text,
  num_associated_deals numeric,
  recent_deal_amount numeric,
  recent_deal_close_date timestamptz,
  total_revenue numeric,
  status_summit_2026 text,
  summit_papel_2025 text,
  hs_linkedin_url text,
  firstname text,
  lastname text,
  email text,
  jobtitle text,
  company text,
  phone text,
  hs_whatsapp_phone_number text,
  hs_email_domain text,
  lifecyclestage text,
  hs_lead_status text,
  hubspot_owner_id text,
  lead_icp text,
  icp text,
  lead_tier text,
  motivo_do_lead__perdido text,
  msclkid text,
  li_fat_id text,
  intent_signals text,
  produto_de_interesse text,
  utm_campaign text,
  utm_source text,
  utm_medium text,
  utm_content text,
  utm_term text,
  summit__categoria_2025 text,
  summit__categoria_2026 text,
  summit__papel_2026 text,
  summit__tipo_entrada_2025 text,
  summit__tipo_entrada_2026 text,
  summit__categoria_do_ingresso_2027 text,
  sincronizado_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
comment on table crm.contato_espelho is 'Espelho das propriedades do contato no HubSpot. NAO e identidade canonica -- crm.pessoas e. Serve para o agente ler o que o HubSpot ja sabe antes de escrever, e para montar o payload do formulario com o melhor dado.';

create table if not exists crm.negocios (
  id uuid primary key default gen_random_uuid(),
  pessoa_id uuid references crm.pessoas(id) on delete set null,
  hubspot_deal_id text not null unique,
  produto_codigo text references catalogo.produtos(codigo),
  createdate timestamptz,
  hs_v2_date_entered_current_stage timestamptz,
  dealname text,
  hs_updated_by_user_id numeric,
  hs_is_closed boolean,
  hs_is_closed_lost boolean,
  hs_deal_stage_probability numeric,
  produto text,
  hubspot_owner_id text,
  hubspot_owner_assigneddate timestamptz,
  hs_forecast_amount numeric,
  amount numeric,
  notes_last_updated timestamptz,
  hs_lastmodifieddate timestamptz,
  dealstage text,
  num_notes numeric,
  pipeline text,
  temperatura text,
  lead_b2c_ou_b2b text,
  origem_do_lead text,
  quantidade_ingressos numeric,
  num_associated_contacts numeric,
  sincronizado_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
comment on table crm.negocios is 'Negocios no pipeline de LEADS (Pipeline de vendas - Summit, 917379159). E aqui que o agente procura negocio ABERTO antes de decidir se preenche o formulario. Nunca no historico.';

create table if not exists crm.negocios_historicos (
  id uuid primary key default gen_random_uuid(),
  pessoa_id uuid references crm.pessoas(id) on delete set null,
  hubspot_deal_id text not null unique,
  produto_codigo text references catalogo.produtos(codigo),
  pipeline text,
  dealname text,
  bandeira_cartao text,
  cupom_utilizado text,
  data_da_compra date,
  data_do_pagamento date,
  hs_is_closed boolean,
  hs_closed_won_count numeric,
  hs_is_closed_count numeric,
  houve_upgrade text,
  id_da_compra text,
  mind_deal_id text,
  eduzz_product_id text,
  metodo_pagamento text,
  modalidade_comercial text,
  num_associated_contacts numeric,
  numero_parcelas numeric,
  hs_deal_stage_probability numeric,
  produto text,
  status_de_pagamento text,
  summit_categoria text,
  summit_lote text,
  summit_year text,
  tipo_de_acesso text,
  tipo_de_venda text,
  valor_com_juros numeric,
  valor_do_desconto numeric,
  amount_in_home_currency numeric,
  quantidade_ingressos numeric,
  houve_reembolso text,
  valor_reembolsado numeric,
  data_reembolso date,
  hs_lastmodifieddate timestamptz,
  hs_analytics_source text,
  hs_analytics_source_data_1 text,
  hs_analytics_source_data_2 text,
  hs_analytics_latest_source text,
  hs_analytics_latest_source_data_1 text,
  hs_analytics_latest_source_data_2 text,
  hs_analytics_latest_source_timestamp timestamptz,
  sincronizado_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
comment on table crm.negocios_historicos is 'Negocios FECHADOS do pipeline Vendas Historicas Mind Summit (default). Somente leitura, atualizado diariamente. Serve de CONTEXTO -- o que a pessoa ja comprou na vida. O agente NUNCA procura negocio aberto aqui, e NUNCA escreve aqui.';

-- Indices de busca: e por aqui que o agente pergunta "essa pessoa ja existe?"
create index if not exists contato_espelho_pessoa_idx on crm.contato_espelho (pessoa_id);
create index if not exists contato_espelho_email_idx  on crm.contato_espelho (lower(email));
create index if not exists contato_espelho_phone_idx  on crm.contato_espelho (phone);

-- "tem negocio ABERTO nesse pipeline?" -- a pergunta que decide se o formulario vai
create index if not exists negocios_pessoa_pipeline_idx on crm.negocios (pessoa_id, pipeline);
create index if not exists negocios_abertos_idx on crm.negocios (pessoa_id)
  where hs_is_closed is not true;

-- historico: so leitura de contexto, sempre pela pessoa
create index if not exists negocios_hist_pessoa_idx on crm.negocios_historicos (pessoa_id);
create index if not exists negocios_hist_ano_idx on crm.negocios_historicos (pessoa_id, summit_year);

-- Qual pipeline trata cada produto. O agente pergunta ao catalogo, nunca sabe o id de cor.
alter table catalogo.produtos add column if not exists pipeline_hubspot text;
comment on column catalogo.produtos.pipeline_hubspot is
  'Id do pipeline do HubSpot onde nascem os negocios deste produto. O agente so enxerga o pipeline que o catalogo autorizar -- e o que protege os 7.092 negocios do historico.';